#!/bin/sh
echo "Updating version.cc"
echo "#include <iostream>"> src/version.cc; echo "char version[]=\" `hg log -l 1 |sed '/^$/d'|tr '\\n' '\t'|sed 's/\\\\/\\\\n/g'` \";">>src/version.cc; echo "void print_version() { std::cout << version;}">>src/version.cc
